-- =====================================================================
-- V44: Allow NULL actor_user_id on audit_events for system actions
-- =====================================================================
-- Context:
--   The original V29 schema declared actor_user_id NOT NULL on the
--   assumption that every audit row had a human actor. The bed-hold-integrity
--   change (Issue #102 RCA) introduces system-driven audit events written
--   by the reconciliation tasklet AND by the V45 one-time backfill
--   migration — both have no human actor and need actor_user_id = NULL.
--
--   Existing callers (TotpController.disableTotpForUser,
--   TotpController.regenerateBackupCodes) already pass null as actor in
--   the AuditEventRecord constructor — those calls would fail under the
--   old NOT NULL constraint if the audit listener actually executed
--   them in production. This migration aligns the schema with the
--   already-intended semantics.
--
-- Ordering:
--   V44 (this migration) must run BEFORE V45 (backfill) because V45
--   writes audit_events rows with actor_user_id = NULL. Flyway runs
--   migrations in version order, so V44 → V45 is guaranteed.
--
-- Idempotency note:
--   coc-admin-escalation's V42 makes the same schema change (drops
--   NOT NULL on actor_user_id) for the same reason. ALTER COLUMN ...
--   DROP NOT NULL is a Postgres no-op when the column is already
--   nullable, so this migration is safe to run on a database that
--   already has coc-admin-escalation's V42 applied. Whichever branch
--   merges to main first wins; the other's equivalent migration runs
--   as a no-op without errors.
--
-- Cross-link: https://github.com/ccradle/finding-a-bed-tonight/issues/102
-- =====================================================================

ALTER TABLE audit_events ALTER COLUMN actor_user_id DROP NOT NULL;
