#!/usr/bin/env bash
# Phase B pg_policies snapshot generator.
#
# Outputs a deterministic Markdown file documenting:
#   1. All pg_policies in the public schema
#   2. GRANTs on the 7 regulated tables (role_table_grants)
#   3. FORCE-RLS flags (pg_class.relforcerowsecurity)
#   4. SECURITY DEFINER functions (must be empty — D52 governance)
#   5. LEAKPROOF functions in the public schema (per Marcus checkpoint-2 N3)
#
# Usage:
#   FABT_PG_OWNER_URL=... ./phase-b-rls-snapshot.sh > docs/security/pg-policies-snapshot.md
#
# CI drift detection: on every PR touching backend/src/main/resources/db/migration/,
# regenerate this file from a fresh Testcontainers Postgres + diff against
# the committed copy. Any difference = policy drift that must be reviewed.

set -euo pipefail

: "${FABT_PG_OWNER_URL:?FABT_PG_OWNER_URL unset}"

run_psql() {
    psql "$FABT_PG_OWNER_URL" -tA -F '|' -P pager=off --set=ON_ERROR_STOP=1 -c "$1"
}

cat <<EOF
# pg_policies snapshot — Phase B (V67–V72 applied)

> Auto-generated by scripts/phase-b-rls-snapshot.sh.
> Regenerate after ANY migration that adds/changes policies, grants, FORCE RLS,
> SECURITY DEFINER functions, or LEAKPROOF functions.
>
> CI drift guard regenerates on each PR and diffs against this file.
>
> Last regenerated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

## Section 1 — pg_policies (public schema)

Fields: schemaname | tablename | policyname | permissive | roles | cmd | qual | with_check

\`\`\`
$(run_psql "
    SELECT schemaname, tablename, policyname, permissive,
           array_to_string(roles, ','),
           cmd, qual, with_check
    FROM pg_policies
    WHERE schemaname = 'public'
    ORDER BY tablename, cmd, permissive DESC, policyname
")
\`\`\`

## Section 2 — GRANTs on the 7 regulated tables

Fields: grantee | table_name | privilege_type | is_grantable

\`\`\`
$(run_psql "
    SELECT grantee, table_name, privilege_type, is_grantable
    FROM information_schema.role_table_grants
    WHERE table_schema = 'public'
      AND table_name IN (
        'audit_events', 'hmis_audit_log', 'password_reset_token',
        'one_time_access_code', 'hmis_outbox',
        'tenant_key_material', 'kid_to_tenant_key'
      )
    ORDER BY table_name, grantee, privilege_type
")
\`\`\`

**Expected for V70 + V72 revokes:** fabt_app MUST NOT appear with UPDATE,
DELETE, TRUNCATE, or REFERENCES on audit_events or hmis_audit_log.

## Section 3 — FORCE RLS flags

Fields: relname | relforcerowsecurity | relrowsecurity

\`\`\`
$(run_psql "
    SELECT c.relname, c.relforcerowsecurity, c.relrowsecurity
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relrowsecurity = true
    ORDER BY c.relname
")
\`\`\`

All 7 regulated tables MUST show relforcerowsecurity=t.

## Section 4 — SECURITY DEFINER functions (D52 — MUST be empty)

Fields: schema | name | prosecdef

\`\`\`
$(run_psql "
    SELECT n.nspname, p.proname, p.prosecdef
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.prosecdef = true
    ORDER BY p.proname
")
\`\`\`

If rows appear here, a migration introduced a SECURITY DEFINER function
without following the D52 governance process (require \`@security-definer-
exception: <justification>\` header on the migration).

## Section 5 — LEAKPROOF functions (Marcus checkpoint-2 N3)

Fields: schema | name | proleakproof | provolatile | proparallel

\`\`\`
$(run_psql "
    SELECT n.nspname, p.proname, p.proleakproof, p.provolatile, p.proparallel
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.proleakproof = true
    ORDER BY p.proname
")
\`\`\`

fabt_current_tenant_id MUST appear with proleakproof=t, provolatile=s, proparallel=s.
Any other public-schema LEAKPROOF function requires review — LEAKPROOF is
an operator-asserted trust marker, not an automatic property.

EOF
